# Python Slicing and Indexing Exmples

Similar to Matlab, Python has very powerful matrix/vector/array manipulations and indexing capabilities.  Python arrays and lists are indexed from 0, which is a lot more natural than Matlab's convention of indexing from 1.  

Let's explore a few ideas via examples

## Lists vs. Arrays
Python uses a data structure called a list and numpy uses arrays.  This are similar in many ways, but numpy arrays are similar to arrays in Matlab and allow for natural math operations.  Below is one example of the different behaivor for lists/arrays in Python:

In [65]:
import numpy as np

a = [ 1, 2, 3]              ## a is a list
x = np.asarray([1, 2, 3])   ## x is an array

print(f'a: {a}')
print(f'x: {x}')

a: [1, 2, 3]
x: [1 2 3]


Multiplying an array by a number multiples each element.  Multiply a list by a number (int) replicates the array that many times

In [66]:
b = 2 * a
print(f'b: {b}')

# b = 2.1 * a     ### throws error
b = -2 * a        ### b is empty
print(f'b: {b}')

b: [1, 2, 3, 1, 2, 3]
b: []


Multiplying a numpy array works as you would expect in scalar-matrix algebra:

In [67]:
y = 2 * x
print(f'y: {y}')

y = 2.1 * x
print(f'y: {y}')

y = -1 * x
print(f'y: {y}')

y: [2 4 6]
y: [2.1 4.2 6.3]
y: [-1 -2 -3]


Since we are focused on "numerical Python", we will use numpy arrays.  When a numpy routine returns an array-like object it is a numpy arrary.  When a numpy routine takes an array-like object as input, it will often accept a list.  To convert a list to a numpy array use:

In [68]:
a = [i for i in range(4)]
x = np.asarray(a)

print(f'a: {a}')
print(f'a-type: {type(a)}')

print(f'\nx: {x}')
print(f'x-type: {type(x)}')

y = np.arange(10)
print(f'\ny: {y}')
print(f'y-type: {type(y)}')


a: [0, 1, 2, 3]
a-type: <class 'list'>

x: [0 1 2 3]
x-type: <class 'numpy.ndarray'>

y: [0 1 2 3 4 5 6 7 8 9]
y-type: <class 'numpy.ndarray'>


Multiplying two arrays is doen element by element.  There is a routine to compute the inner (dot) product

In [69]:
x = np.arange(4)
y = np.random.normal(0, 1, 4)
print(f'x: {x}')
print(f'y: {y}')

## inner product
z = np.dot(x, y)
print(f'\nz: {z}')

## outer product
v = np.outer(x, y)
print(f'\nv: {v}')


x: [0 1 2 3]
y: [-0.94216087 -2.21318328 -0.94480091  0.08116183]

z: -3.8592996234985426

v: [[-0.         -0.         -0.          0.        ]
 [-0.94216087 -2.21318328 -0.94480091  0.08116183]
 [-1.88432173 -4.42636656 -1.88960183  0.16232366]
 [-2.8264826  -6.63954984 -2.83440274  0.24348549]]


Notice that the inner product is the scalar $\textbf{x}^t \textbf{y}$ and the outer product is the matrix $\textbf{x} \textbf{y}^t$.  So in the above code, `v` is a 2-dimensional numpy array.  We can check the sahpe of an array and for a 2D array, we can access the ith row or column (viewing as a matrix):

In [70]:
x = np.arange(18)
print(f'x: {x}')
print(f'x-shape: {x.shape}')

x = x.reshape((3, 6))
print(f'\nx: {x}')
print(f'x-shape: {x.shape}')

# second row in x
print(f'\nx[1]: {x[1]}')
print(f'x[1]-shape: {x[1].shape}')

# second column in x using the transpose method for numpy arrays
print(f'\nx.T[1]: {x.T[1]}')
print(f'x.T[1]-shape: {x.T[1].shape}')


x: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x-shape: (18,)

x: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
x-shape: (3, 6)

x[1]: [ 6  7  8  9 10 11]
x[1]-shape: (6,)

x.T[1]: [ 1  7 13]
x.T[1]-shape: (3,)


Numpy allows for matrix-matrix multiplication and matrix-vector multiplication:

In [71]:
w = np.arange(6)
print(f'w: {w}')
print(f'w-shape: {w.shape}')

A = np.arange(18).reshape((3,6)) + 4
print(f'\nA: {A}')
print(f'A-shape: {A.shape}')

### matrix-vector multiplication
z = A @ w
print(f'\nz: {z}')
print(f'z-shape: {z.shape}')

# this multiplies the j-th column of A by w[j]
z = A * w
print(f'\nz: {z}')
print(f'z-shape: {z.shape}')

# this multiplies the j-th column of A by w[j]
z = w * A
print(f'\nz: {z}')
print(f'z-shape: {z.shape}')



w: [0 1 2 3 4 5]
w-shape: (6,)

A: [[ 4  5  6  7  8  9]
 [10 11 12 13 14 15]
 [16 17 18 19 20 21]]
A-shape: (3, 6)

z: [115 205 295]
z-shape: (3,)

z: [[  0   5  12  21  32  45]
 [  0  11  24  39  56  75]
 [  0  17  36  57  80 105]]
z-shape: (3, 6)

z: [[  0   5  12  21  32  45]
 [  0  11  24  39  56  75]
 [  0  17  36  57  80 105]]
z-shape: (3, 6)


We can do element-wise functions on a matrix/vector:

In [72]:
print(f'w: {w}')
z = w ** 2 
print(f'\nz: {z}')

z = np.exp(w)
print(f'\nz: {z}')


w: [0 1 2 3 4 5]

z: [ 0  1  4  9 16 25]

z: [  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]


## Slicing and Indexing NumPy Arrays
You can index a portion of an array using "slicing":

In [73]:
x = np.arange(10)
print(f'x: {x}')
print(f'x-shape: {x.shape}')

### the start of an array
print(f'\nx[0:4]: {x[0:4]}')
print(f'x[0:4]-shape: {x[0:4].shape}')

## can drop the first 0
print(f'\nx[:4]: {x[:4]}')
print(f'x[:4]-shape: {x[:4].shape}')

### the end of an array
print(f'\nx[4:]: {x[4:]}')
print(f'x[4:]-shape: {x[4:].shape}')

### the "middle" of an array
print(f'\nx[3:7]: {x[3:7]}')
print(f'x[3:7]-shape: {x[3:7].shape}')

### subsampling an array
print(f'\nx[::2]: {x[::2]}')
print(f'x[::2]-shape: {x[::2].shape}')

print(f'\nx[::3]: {x[::3]}')
print(f'x[::3]-shape: {x[::3].shape}')

## subsampling with negaive step reverses the array
print(f'\nx[::-1]: {x[::-1]}')
print(f'x[::-1]-shape: {x[::-1].shape}')

## reversing, sub-sampling and slicing all in one...
print(f'\nx[8:3:-2]: {x[8:3:-2]}')
print(f'x[8:3:-2]-shape: {x[8:3:-2].shape}')

x: [0 1 2 3 4 5 6 7 8 9]
x-shape: (10,)

x[0:4]: [0 1 2 3]
x[0:4]-shape: (4,)

x[:4]: [0 1 2 3]
x[:4]-shape: (4,)

x[4:]: [4 5 6 7 8 9]
x[4:]-shape: (6,)

x[3:7]: [3 4 5 6]
x[3:7]-shape: (4,)

x[::2]: [0 2 4 6 8]
x[::2]-shape: (5,)

x[::3]: [0 3 6 9]
x[::3]-shape: (4,)

x[::-1]: [9 8 7 6 5 4 3 2 1 0]
x[::-1]-shape: (10,)

x[8:3:-2]: [8 6 4]
x[8:3:-2]-shape: (3,)


We can also access sub-ranges of 2D arrays:

In [74]:
A = np.arange(18).reshape((3, 6))
print(f'A: {A}')
print(f'A-shape: {A.shape}')

### First 3 columns of A
print(f'\nA[:,:3]:\n{A[:,:3]}')
print(f'A[:,:3]-shape: {A[:,:3].shape}')

### First 2 rows of A
print(f'\nA[:2,:]:\n{A[:2,:]}')
print(f'A[:2,:]-shape: {A[:2,:].shape}')

### First 2 rows of A; limited to last 4 columns
print(f'\nA[:2,3:]:\n{A[:2,3:]}')
print(f'A[:2,3:]-shape: {A[:2,3:].shape}')


A: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
A-shape: (3, 6)

A[:,:3]:
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]
A[:,:3]-shape: (3, 3)

A[:2,:]:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
A[:2,:]-shape: (2, 6)

A[:2,3:]:
[[ 3  4  5]
 [ 9 10 11]]
A[:2,3:]-shape: (2, 3)


Many numpy methods operate over the elements of the array.  For multi-dimensional arrays, we can specify and axis and also use the sub-range indexing methods to operate over sup-ranges of the array.  

In [75]:
A = np.arange(18).reshape((3, 6))
print(f'A: {A}')
print(f'A-shape: {A.shape}')

### sum all the elements
s = np.sum(A)
print(f'\ns:\n{s}')

print('\nsum down columns:')
s = np.sum(A, axis = 0)
print(f's:\n{s}')
print(f's-shape: {s.shape}')

print('\nsum across rows:')
s = np.sum(A, axis = 1)
print(f's:\n{s}')
print(f's-shape: {s.shape}')

print('\nsum across rows, limited column range:')
s = np.sum(A[:, 2:4], axis = 1)
print(f's:\n{s}')
print(f's-shape: {s.shape}')



A: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
A-shape: (3, 6)

s:
153

sum down columns:
s:
[18 21 24 27 30 33]
s-shape: (6,)

sum across rows:
s:
[15 51 87]
s-shape: (3,)

sum across rows, limited column range:
s:
[ 5 17 29]
s-shape: (3,)


# Python Gotchas
There are a couple of common issues in python that sometimes are gotchas for new users.  One of these is that python assignments are by reference (think pointers).  This means that an assignment is not a deep copy and just a reference back to the original.  This illustrated in the following example:

In [76]:
x = np.arange(5)
y = x
print(f'x: {x}')
print(f'y: {y}')

x[1] = -10
print(f'x: {x}')
print(f'y: {y}')
print('notice that y[1] changed with the assignment of x[1]')

x = np.arange(5)
y = np.copy(x)
x[1] = -10
print(f'x: {x}')
print(f'y: {y}')
print('notice that y[1] did not change with the assignment of x[1]')


x: [0 1 2 3 4]
y: [0 1 2 3 4]
x: [  0 -10   2   3   4]
y: [  0 -10   2   3   4]
notice that y[1] changed with the assignment of x[1]
x: [  0 -10   2   3   4]
y: [0 1 2 3 4]
notice that y[1] did not change with the assignment of x[1]


Another potential gotcha is that you can assign to pretty much anything in python.  This can lead to bad consequences if you make a mistake.  Here's an example:

In [77]:
## this is an error because np.sin() has been reassigned to be the integer 2 and is therefore not a function anymore!
np.sin = 2
y = np.sin(np.pi / 3)
print(f'y: {y}') 


TypeError: 'int' object is not callable